-- GENERATED by src/lean_gen_detq.py from detq_check.py's wall forms. Do not edit by hand.
-- [P104]: every wall splits over Q because det(Q) is a perfect square identically.
-- The matrices below are sympy's; everything they are checked AGAINST is computed by Lean.

namespace Cube.Detq

/-- the rotation matrix of the Cayley parameter (x, y, z), times N = 1 + x^2 + y^2 + z^2 -/
def Mr (x y z : Int) : Fin 3 → Fin 3 → Int
  | 0, 0 => 1 + x^2 - y^2 - z^2 | 0, 1 => 2*(x*y - z)         | 0, 2 => 2*(x*z + y)
  | 1, 0 => 2*(x*y + z)         | 1, 1 => 1 - x^2 + y^2 - z^2 | 1, 2 => 2*(y*z - x)
  | 2, 0 => 2*(x*z - y)         | 2, 1 => 2*(y*z + x)         | 2, 2 => 1 - x^2 - y^2 + z^2
def Nn (x y z : Int) : Int := 1 + x^2 + y^2 + z^2

/-- 3x3 determinant of the columns (a, b, c) -/
def det3 (a b c : Fin 3 → Int) : Int :=
  a 0 * (b 1 * c 2 - b 2 * c 1) - b 0 * (a 1 * c 2 - a 2 * c 1) + c 0 * (a 1 * b 2 - a 2 * b 1)

/-- 4x4 determinant, cofactor expansion along row 0 -/
def det4 (q : Fin 4 → Fin 4 → Int) : Int :=
  let m (i j k : Fin 4) : Int :=
    q 1 i * (q 2 j * q 3 k - q 2 k * q 3 j) - q 1 j * (q 2 i * q 3 k - q 2 k * q 3 i)
      + q 1 k * (q 2 i * q 3 j - q 2 j * q 3 i)
  q 0 0 * m 1 2 3 - q 0 1 * m 0 2 3 + q 0 2 * m 0 1 3 - q 0 3 * m 0 1 2

/-- the quadratic form of q at (x, y, z, 1) -/
def qf (q : Fin 4 → Fin 4 → Int) (x y z : Int) : Int :=
  let v : Fin 4 → Int := fun | 0 => x | 1 => y | 2 => z | 3 => 1
  (v 0 * (q 0 0 * v 0 + q 0 1 * v 1 + q 0 2 * v 2 + q 0 3 * v 3))
  + (v 1 * (q 1 0 * v 0 + q 1 1 * v 1 + q 1 2 * v 2 + q 1 3 * v 3))
  + (v 2 * (q 2 0 * v 0 + q 2 1 * v 1 + q 2 2 * v 2 + q 2 3 * v 3))
  + (v 3 * (q 3 0 * v 0 + q 3 1 * v 1 + q 3 2 * v 2 + q 3 3 * v 3))

def Q_W4_axis0_pos (p1 p2 p3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (2*p1 - 2)
  | 0, 1 => (2*p2)
  | 0, 2 => (2*p3)
  | 0, 3 => (0)
  | 1, 0 => (2*p2)
  | 1, 1 => (-2*p1 - 2)
  | 1, 2 => (0)
  | 1, 3 => (-2*p3)
  | 2, 0 => (2*p3)
  | 2, 1 => (0)
  | 2, 2 => (-2*p1 - 2)
  | 2, 3 => (2*p2)
  | 3, 0 => (0)
  | 3, 1 => (-2*p3)
  | 3, 2 => (2*p2)
  | 3, 3 => (2*p1 - 2)
theorem W4_axis0_pos_form (x y z p1 p2 p3 : Int) :
    2 * (p1 * Mr x y z 0 0 + p2 * Mr x y z 1 0 + p3 * Mr x y z 2 0 - (1) * Nn x y z) = qf (Q_W4_axis0_pos p1 p2 p3) x y z := by
  simp only [qf, Q_W4_axis0_pos, Mr, Nn]; grind
theorem W4_axis0_pos_det (p1 p2 p3 : Int) :
    det4 (Q_W4_axis0_pos p1 p2 p3) = 16 * (p1^2 + p2^2 + p3^2 - 1)^2 := by
  simp only [det4, Q_W4_axis0_pos]; grind

def Q_W4_axis0_neg (p1 p2 p3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (2*p1 + 2)
  | 0, 1 => (2*p2)
  | 0, 2 => (2*p3)
  | 0, 3 => (0)
  | 1, 0 => (2*p2)
  | 1, 1 => (2 - 2*p1)
  | 1, 2 => (0)
  | 1, 3 => (-2*p3)
  | 2, 0 => (2*p3)
  | 2, 1 => (0)
  | 2, 2 => (2 - 2*p1)
  | 2, 3 => (2*p2)
  | 3, 0 => (0)
  | 3, 1 => (-2*p3)
  | 3, 2 => (2*p2)
  | 3, 3 => (2*p1 + 2)
theorem W4_axis0_neg_form (x y z p1 p2 p3 : Int) :
    2 * (p1 * Mr x y z 0 0 + p2 * Mr x y z 1 0 + p3 * Mr x y z 2 0 - (-1) * Nn x y z) = qf (Q_W4_axis0_neg p1 p2 p3) x y z := by
  simp only [qf, Q_W4_axis0_neg, Mr, Nn]; grind
theorem W4_axis0_neg_det (p1 p2 p3 : Int) :
    det4 (Q_W4_axis0_neg p1 p2 p3) = 16 * (p1^2 + p2^2 + p3^2 - 1)^2 := by
  simp only [det4, Q_W4_axis0_neg]; grind

def Q_W4_axis1_pos (p1 p2 p3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (-2*p2 - 2)
  | 0, 1 => (2*p1)
  | 0, 2 => (0)
  | 0, 3 => (2*p3)
  | 1, 0 => (2*p1)
  | 1, 1 => (2*p2 - 2)
  | 1, 2 => (2*p3)
  | 1, 3 => (0)
  | 2, 0 => (0)
  | 2, 1 => (2*p3)
  | 2, 2 => (-2*p2 - 2)
  | 2, 3 => (-2*p1)
  | 3, 0 => (2*p3)
  | 3, 1 => (0)
  | 3, 2 => (-2*p1)
  | 3, 3 => (2*p2 - 2)
theorem W4_axis1_pos_form (x y z p1 p2 p3 : Int) :
    2 * (p1 * Mr x y z 0 1 + p2 * Mr x y z 1 1 + p3 * Mr x y z 2 1 - (1) * Nn x y z) = qf (Q_W4_axis1_pos p1 p2 p3) x y z := by
  simp only [qf, Q_W4_axis1_pos, Mr, Nn]; grind
theorem W4_axis1_pos_det (p1 p2 p3 : Int) :
    det4 (Q_W4_axis1_pos p1 p2 p3) = 16 * (p1^2 + p2^2 + p3^2 - 1)^2 := by
  simp only [det4, Q_W4_axis1_pos]; grind

def Q_W4_axis1_neg (p1 p2 p3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (2 - 2*p2)
  | 0, 1 => (2*p1)
  | 0, 2 => (0)
  | 0, 3 => (2*p3)
  | 1, 0 => (2*p1)
  | 1, 1 => (2*p2 + 2)
  | 1, 2 => (2*p3)
  | 1, 3 => (0)
  | 2, 0 => (0)
  | 2, 1 => (2*p3)
  | 2, 2 => (2 - 2*p2)
  | 2, 3 => (-2*p1)
  | 3, 0 => (2*p3)
  | 3, 1 => (0)
  | 3, 2 => (-2*p1)
  | 3, 3 => (2*p2 + 2)
theorem W4_axis1_neg_form (x y z p1 p2 p3 : Int) :
    2 * (p1 * Mr x y z 0 1 + p2 * Mr x y z 1 1 + p3 * Mr x y z 2 1 - (-1) * Nn x y z) = qf (Q_W4_axis1_neg p1 p2 p3) x y z := by
  simp only [qf, Q_W4_axis1_neg, Mr, Nn]; grind
theorem W4_axis1_neg_det (p1 p2 p3 : Int) :
    det4 (Q_W4_axis1_neg p1 p2 p3) = 16 * (p1^2 + p2^2 + p3^2 - 1)^2 := by
  simp only [det4, Q_W4_axis1_neg]; grind

def Q_W4_axis2_pos (p1 p2 p3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (-2*p3 - 2)
  | 0, 1 => (0)
  | 0, 2 => (2*p1)
  | 0, 3 => (-2*p2)
  | 1, 0 => (0)
  | 1, 1 => (-2*p3 - 2)
  | 1, 2 => (2*p2)
  | 1, 3 => (2*p1)
  | 2, 0 => (2*p1)
  | 2, 1 => (2*p2)
  | 2, 2 => (2*p3 - 2)
  | 2, 3 => (0)
  | 3, 0 => (-2*p2)
  | 3, 1 => (2*p1)
  | 3, 2 => (0)
  | 3, 3 => (2*p3 - 2)
theorem W4_axis2_pos_form (x y z p1 p2 p3 : Int) :
    2 * (p1 * Mr x y z 0 2 + p2 * Mr x y z 1 2 + p3 * Mr x y z 2 2 - (1) * Nn x y z) = qf (Q_W4_axis2_pos p1 p2 p3) x y z := by
  simp only [qf, Q_W4_axis2_pos, Mr, Nn]; grind
theorem W4_axis2_pos_det (p1 p2 p3 : Int) :
    det4 (Q_W4_axis2_pos p1 p2 p3) = 16 * (p1^2 + p2^2 + p3^2 - 1)^2 := by
  simp only [det4, Q_W4_axis2_pos]; grind

def Q_W4_axis2_neg (p1 p2 p3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (2 - 2*p3)
  | 0, 1 => (0)
  | 0, 2 => (2*p1)
  | 0, 3 => (-2*p2)
  | 1, 0 => (0)
  | 1, 1 => (2 - 2*p3)
  | 1, 2 => (2*p2)
  | 1, 3 => (2*p1)
  | 2, 0 => (2*p1)
  | 2, 1 => (2*p2)
  | 2, 2 => (2*p3 + 2)
  | 2, 3 => (0)
  | 3, 0 => (-2*p2)
  | 3, 1 => (2*p1)
  | 3, 2 => (0)
  | 3, 3 => (2*p3 + 2)
theorem W4_axis2_neg_form (x y z p1 p2 p3 : Int) :
    2 * (p1 * Mr x y z 0 2 + p2 * Mr x y z 1 2 + p3 * Mr x y z 2 2 - (-1) * Nn x y z) = qf (Q_W4_axis2_neg p1 p2 p3) x y z := by
  simp only [qf, Q_W4_axis2_neg, Mr, Nn]; grind
theorem W4_axis2_neg_det (p1 p2 p3 : Int) :
    det4 (Q_W4_axis2_neg p1 p2 p3) = 16 * (p1^2 + p2^2 + p3^2 - 1)^2 := by
  simp only [det4, Q_W4_axis2_neg]; grind

def Q_W3_edge0_pp (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m2*q3 + 4*m2 - 4*m3*q2 - 4*m3)
  | 0, 1 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 0, 2 => (4*m1*q2 + 4*m1 - 4*m2*q1)
  | 0, 3 => (-4*m2 - 4*m3)
  | 1, 0 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 1, 1 => (-4*m2*q3 - 4*m2 + 4*m3*q2 - 4*m3)
  | 1, 2 => (4*m2 - 4*m3)
  | 1, 3 => (-4*m1*q2 + 4*m1 + 4*m2*q1)
  | 2, 0 => (4*m1*q2 + 4*m1 - 4*m2*q1)
  | 2, 1 => (4*m2 - 4*m3)
  | 2, 2 => (-4*m2*q3 + 4*m2 + 4*m3*q2 + 4*m3)
  | 2, 3 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 3, 0 => (-4*m2 - 4*m3)
  | 3, 1 => (-4*m1*q2 + 4*m1 + 4*m2*q1)
  | 3, 2 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 3, 3 => (4*m2*q3 - 4*m2 - 4*m3*q2 + 4*m3)
theorem W3_edge0_pp_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 0) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((1) * Mr x y z r 1 + (1) * Mr x y z r 2 - Mr x y z r 0)) = Nn x y z * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z - 4*m1*x*y + 4*m1*x*z + 4*m1*y + 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 + 2*m2*x^2 - 4*m2*x - 2*m2*y^2 + 4*m2*y*z + 2*m2*z^2 - 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 - 2*m3*x^2 - 4*m3*x - 2*m3*y^2 - 4*m3*y*z + 2*m3*z^2 + 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge0_pp_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z - 4*m1*x*y + 4*m1*x*z + 4*m1*y + 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 + 2*m2*x^2 - 4*m2*x - 2*m2*y^2 + 4*m2*y*z + 2*m2*z^2 - 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 - 2*m3*x^2 - 4*m3*x - 2*m3*y^2 - 4*m3*y*z + 2*m3*z^2 + 2*m3) = qf (Q_W3_edge0_pp q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge0_pp]; grind
theorem W3_edge0_pp_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge0_pp q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge0_pp]; grind

def Q_W3_edge0_pm (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m2*q3 - 4*m2 - 4*m3*q2 - 4*m3)
  | 0, 1 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 0, 2 => (4*m1*q2 + 4*m1 - 4*m2*q1)
  | 0, 3 => (-4*m2 + 4*m3)
  | 1, 0 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 1, 1 => (-4*m2*q3 + 4*m2 + 4*m3*q2 - 4*m3)
  | 1, 2 => (4*m2 + 4*m3)
  | 1, 3 => (-4*m1*q2 + 4*m1 + 4*m2*q1)
  | 2, 0 => (4*m1*q2 + 4*m1 - 4*m2*q1)
  | 2, 1 => (4*m2 + 4*m3)
  | 2, 2 => (-4*m2*q3 - 4*m2 + 4*m3*q2 + 4*m3)
  | 2, 3 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 3, 0 => (-4*m2 + 4*m3)
  | 3, 1 => (-4*m1*q2 + 4*m1 + 4*m2*q1)
  | 3, 2 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 3, 3 => (4*m2*q3 + 4*m2 - 4*m3*q2 + 4*m3)
theorem W3_edge0_pm_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 0) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((1) * Mr x y z r 1 + (-1) * Mr x y z r 2 - Mr x y z r 0)) = Nn x y z * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z + 4*m1*x*y + 4*m1*x*z + 4*m1*y - 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 - 2*m2*x^2 - 4*m2*x + 2*m2*y^2 + 4*m2*y*z - 2*m2*z^2 + 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 - 2*m3*x^2 + 4*m3*x - 2*m3*y^2 + 4*m3*y*z + 2*m3*z^2 + 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge0_pm_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z + 4*m1*x*y + 4*m1*x*z + 4*m1*y - 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 - 2*m2*x^2 - 4*m2*x + 2*m2*y^2 + 4*m2*y*z - 2*m2*z^2 + 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 - 2*m3*x^2 + 4*m3*x - 2*m3*y^2 + 4*m3*y*z + 2*m3*z^2 + 2*m3) = qf (Q_W3_edge0_pm q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge0_pm]; grind
theorem W3_edge0_pm_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge0_pm q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge0_pm]; grind

def Q_W3_edge0_mp (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m2*q3 + 4*m2 - 4*m3*q2 + 4*m3)
  | 0, 1 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 0, 2 => (4*m1*q2 - 4*m1 - 4*m2*q1)
  | 0, 3 => (4*m2 - 4*m3)
  | 1, 0 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 1, 1 => (-4*m2*q3 - 4*m2 + 4*m3*q2 + 4*m3)
  | 1, 2 => (-4*m2 - 4*m3)
  | 1, 3 => (-4*m1*q2 - 4*m1 + 4*m2*q1)
  | 2, 0 => (4*m1*q2 - 4*m1 - 4*m2*q1)
  | 2, 1 => (-4*m2 - 4*m3)
  | 2, 2 => (-4*m2*q3 + 4*m2 + 4*m3*q2 - 4*m3)
  | 2, 3 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 3, 0 => (4*m2 - 4*m3)
  | 3, 1 => (-4*m1*q2 - 4*m1 + 4*m2*q1)
  | 3, 2 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 3, 3 => (4*m2*q3 - 4*m2 - 4*m3*q2 - 4*m3)
theorem W3_edge0_mp_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 0) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((-1) * Mr x y z r 1 + (1) * Mr x y z r 2 - Mr x y z r 0)) = Nn x y z * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z - 4*m1*x*y - 4*m1*x*z - 4*m1*y + 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 + 2*m2*x^2 + 4*m2*x - 2*m2*y^2 - 4*m2*y*z + 2*m2*z^2 - 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 + 2*m3*x^2 - 4*m3*x + 2*m3*y^2 - 4*m3*y*z - 2*m3*z^2 - 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge0_mp_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z - 4*m1*x*y - 4*m1*x*z - 4*m1*y + 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 + 2*m2*x^2 + 4*m2*x - 2*m2*y^2 - 4*m2*y*z + 2*m2*z^2 - 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 + 2*m3*x^2 - 4*m3*x + 2*m3*y^2 - 4*m3*y*z - 2*m3*z^2 - 2*m3) = qf (Q_W3_edge0_mp q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge0_mp]; grind
theorem W3_edge0_mp_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge0_mp q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge0_mp]; grind

def Q_W3_edge0_mm (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m2*q3 - 4*m2 - 4*m3*q2 + 4*m3)
  | 0, 1 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 0, 2 => (4*m1*q2 - 4*m1 - 4*m2*q1)
  | 0, 3 => (4*m2 + 4*m3)
  | 1, 0 => (-4*m1*q3 + 4*m1 + 4*m3*q1)
  | 1, 1 => (-4*m2*q3 + 4*m2 + 4*m3*q2 + 4*m3)
  | 1, 2 => (-4*m2 + 4*m3)
  | 1, 3 => (-4*m1*q2 - 4*m1 + 4*m2*q1)
  | 2, 0 => (4*m1*q2 - 4*m1 - 4*m2*q1)
  | 2, 1 => (-4*m2 + 4*m3)
  | 2, 2 => (-4*m2*q3 - 4*m2 + 4*m3*q2 - 4*m3)
  | 2, 3 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 3, 0 => (4*m2 + 4*m3)
  | 3, 1 => (-4*m1*q2 - 4*m1 + 4*m2*q1)
  | 3, 2 => (-4*m1*q3 - 4*m1 + 4*m3*q1)
  | 3, 3 => (4*m2*q3 + 4*m2 - 4*m3*q2 - 4*m3)
theorem W3_edge0_mm_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 0) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((-1) * Mr x y z r 1 + (-1) * Mr x y z r 2 - Mr x y z r 0)) = Nn x y z * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z + 4*m1*x*y - 4*m1*x*z - 4*m1*y - 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 - 2*m2*x^2 + 4*m2*x + 2*m2*y^2 - 4*m2*y*z - 2*m2*z^2 + 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 + 2*m3*x^2 + 4*m3*x + 2*m3*y^2 + 4*m3*y*z - 2*m3*z^2 - 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge0_mm_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x*z - 4*m1*q2*y - 4*m1*q3*x*y - 4*m1*q3*z + 4*m1*x*y - 4*m1*x*z - 4*m1*y - 4*m1*z - 4*m2*q1*x*z + 4*m2*q1*y + 2*m2*q3*x^2 - 2*m2*q3*y^2 - 2*m2*q3*z^2 + 2*m2*q3 - 2*m2*x^2 + 4*m2*x + 2*m2*y^2 - 4*m2*y*z - 2*m2*z^2 + 2*m2 + 4*m3*q1*x*y + 4*m3*q1*z - 2*m3*q2*x^2 + 2*m3*q2*y^2 + 2*m3*q2*z^2 - 2*m3*q2 + 2*m3*x^2 + 4*m3*x + 2*m3*y^2 + 4*m3*y*z - 2*m3*z^2 - 2*m3) = qf (Q_W3_edge0_mm q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge0_mm]; grind
theorem W3_edge0_mm_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge0_mm q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge0_mm]; grind

def Q_W3_edge1_pp (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m1*q3 + 4*m1 - 4*m3*q1 + 4*m3)
  | 0, 1 => (4*m2*q3 + 4*m2 - 4*m3*q2)
  | 0, 2 => (-4*m1 + 4*m3)
  | 0, 3 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 1, 0 => (4*m2*q3 + 4*m2 - 4*m3*q2)
  | 1, 1 => (-4*m1*q3 - 4*m1 + 4*m3*q1 + 4*m3)
  | 1, 2 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 1, 3 => (-4*m1 - 4*m3)
  | 2, 0 => (-4*m1 + 4*m3)
  | 2, 1 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 2, 2 => (4*m1*q3 - 4*m1 - 4*m3*q1 - 4*m3)
  | 2, 3 => (-4*m2*q3 + 4*m2 + 4*m3*q2)
  | 3, 0 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 3, 1 => (-4*m1 - 4*m3)
  | 3, 2 => (-4*m2*q3 + 4*m2 + 4*m3*q2)
  | 3, 3 => (-4*m1*q3 + 4*m1 + 4*m3*q1 - 4*m3)
theorem W3_edge1_pp_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 1) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((1) * Mr x y z r 0 + (1) * Mr x y z r 2 - Mr x y z r 1)) = Nn x y z * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 + 2*m1*x^2 - 4*m1*x*z - 2*m1*y^2 - 4*m1*y - 2*m1*z^2 + 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z + 4*m2*x*y + 4*m2*x - 4*m2*y*z + 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z + 2*m3*x^2 + 4*m3*x*z + 2*m3*y^2 - 4*m3*y - 2*m3*z^2 - 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge1_pp_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 + 2*m1*x^2 - 4*m1*x*z - 2*m1*y^2 - 4*m1*y - 2*m1*z^2 + 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z + 4*m2*x*y + 4*m2*x - 4*m2*y*z + 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z + 2*m3*x^2 + 4*m3*x*z + 2*m3*y^2 - 4*m3*y - 2*m3*z^2 - 2*m3) = qf (Q_W3_edge1_pp q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge1_pp]; grind
theorem W3_edge1_pp_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge1_pp q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge1_pp]; grind

def Q_W3_edge1_pm (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m1*q3 - 4*m1 - 4*m3*q1 + 4*m3)
  | 0, 1 => (4*m2*q3 - 4*m2 - 4*m3*q2)
  | 0, 2 => (-4*m1 - 4*m3)
  | 0, 3 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 1, 0 => (4*m2*q3 - 4*m2 - 4*m3*q2)
  | 1, 1 => (-4*m1*q3 + 4*m1 + 4*m3*q1 + 4*m3)
  | 1, 2 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 1, 3 => (-4*m1 + 4*m3)
  | 2, 0 => (-4*m1 - 4*m3)
  | 2, 1 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 2, 2 => (4*m1*q3 + 4*m1 - 4*m3*q1 - 4*m3)
  | 2, 3 => (-4*m2*q3 - 4*m2 + 4*m3*q2)
  | 3, 0 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 3, 1 => (-4*m1 + 4*m3)
  | 3, 2 => (-4*m2*q3 - 4*m2 + 4*m3*q2)
  | 3, 3 => (-4*m1*q3 - 4*m1 + 4*m3*q1 - 4*m3)
theorem W3_edge1_pm_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 1) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((1) * Mr x y z r 0 + (-1) * Mr x y z r 2 - Mr x y z r 1)) = Nn x y z * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 - 2*m1*x^2 - 4*m1*x*z + 2*m1*y^2 - 4*m1*y + 2*m1*z^2 - 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z - 4*m2*x*y + 4*m2*x - 4*m2*y*z - 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z + 2*m3*x^2 - 4*m3*x*z + 2*m3*y^2 + 4*m3*y - 2*m3*z^2 - 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge1_pm_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 - 2*m1*x^2 - 4*m1*x*z + 2*m1*y^2 - 4*m1*y + 2*m1*z^2 - 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z - 4*m2*x*y + 4*m2*x - 4*m2*y*z - 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z + 2*m3*x^2 - 4*m3*x*z + 2*m3*y^2 + 4*m3*y - 2*m3*z^2 - 2*m3) = qf (Q_W3_edge1_pm q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge1_pm]; grind
theorem W3_edge1_pm_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge1_pm q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge1_pm]; grind

def Q_W3_edge1_mp (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m1*q3 + 4*m1 - 4*m3*q1 - 4*m3)
  | 0, 1 => (4*m2*q3 + 4*m2 - 4*m3*q2)
  | 0, 2 => (4*m1 + 4*m3)
  | 0, 3 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 1, 0 => (4*m2*q3 + 4*m2 - 4*m3*q2)
  | 1, 1 => (-4*m1*q3 - 4*m1 + 4*m3*q1 - 4*m3)
  | 1, 2 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 1, 3 => (4*m1 - 4*m3)
  | 2, 0 => (4*m1 + 4*m3)
  | 2, 1 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 2, 2 => (4*m1*q3 - 4*m1 - 4*m3*q1 + 4*m3)
  | 2, 3 => (-4*m2*q3 + 4*m2 + 4*m3*q2)
  | 3, 0 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 3, 1 => (4*m1 - 4*m3)
  | 3, 2 => (-4*m2*q3 + 4*m2 + 4*m3*q2)
  | 3, 3 => (-4*m1*q3 + 4*m1 + 4*m3*q1 + 4*m3)
theorem W3_edge1_mp_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 1) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((-1) * Mr x y z r 0 + (1) * Mr x y z r 2 - Mr x y z r 1)) = Nn x y z * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 + 2*m1*x^2 + 4*m1*x*z - 2*m1*y^2 + 4*m1*y - 2*m1*z^2 + 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z + 4*m2*x*y - 4*m2*x + 4*m2*y*z + 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z - 2*m3*x^2 + 4*m3*x*z - 2*m3*y^2 - 4*m3*y + 2*m3*z^2 + 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge1_mp_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 + 2*m1*x^2 + 4*m1*x*z - 2*m1*y^2 + 4*m1*y - 2*m1*z^2 + 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z + 4*m2*x*y - 4*m2*x + 4*m2*y*z + 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z - 2*m3*x^2 + 4*m3*x*z - 2*m3*y^2 - 4*m3*y + 2*m3*z^2 + 2*m3) = qf (Q_W3_edge1_mp q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge1_mp]; grind
theorem W3_edge1_mp_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge1_mp q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge1_mp]; grind

def Q_W3_edge1_mm (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (4*m1*q3 - 4*m1 - 4*m3*q1 - 4*m3)
  | 0, 1 => (4*m2*q3 - 4*m2 - 4*m3*q2)
  | 0, 2 => (4*m1 - 4*m3)
  | 0, 3 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 1, 0 => (4*m2*q3 - 4*m2 - 4*m3*q2)
  | 1, 1 => (-4*m1*q3 + 4*m1 + 4*m3*q1 - 4*m3)
  | 1, 2 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 1, 3 => (4*m1 + 4*m3)
  | 2, 0 => (4*m1 - 4*m3)
  | 2, 1 => (4*m1*q2 - 4*m2*q1 + 4*m2)
  | 2, 2 => (4*m1*q3 + 4*m1 - 4*m3*q1 + 4*m3)
  | 2, 3 => (-4*m2*q3 - 4*m2 + 4*m3*q2)
  | 3, 0 => (4*m1*q2 - 4*m2*q1 - 4*m2)
  | 3, 1 => (4*m1 + 4*m3)
  | 3, 2 => (-4*m2*q3 - 4*m2 + 4*m3*q2)
  | 3, 3 => (-4*m1*q3 - 4*m1 + 4*m3*q1 + 4*m3)
theorem W3_edge1_mm_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 1) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((-1) * Mr x y z r 0 + (-1) * Mr x y z r 2 - Mr x y z r 1)) = Nn x y z * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 - 2*m1*x^2 + 4*m1*x*z + 2*m1*y^2 + 4*m1*y + 2*m1*z^2 - 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z - 4*m2*x*y - 4*m2*x + 4*m2*y*z - 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z - 2*m3*x^2 - 4*m3*x*z - 2*m3*y^2 + 4*m3*y + 2*m3*z^2 + 2*m3) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge1_mm_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (4*m1*q2*x + 4*m1*q2*y*z + 2*m1*q3*x^2 - 2*m1*q3*y^2 + 2*m1*q3*z^2 - 2*m1*q3 - 2*m1*x^2 + 4*m1*x*z + 2*m1*y^2 + 4*m1*y + 2*m1*z^2 - 2*m1 - 4*m2*q1*x - 4*m2*q1*y*z + 4*m2*q3*x*y - 4*m2*q3*z - 4*m2*x*y - 4*m2*x + 4*m2*y*z - 4*m2*z - 2*m3*q1*x^2 + 2*m3*q1*y^2 - 2*m3*q1*z^2 + 2*m3*q1 - 4*m3*q2*x*y + 4*m3*q2*z - 2*m3*x^2 - 4*m3*x*z - 2*m3*y^2 + 4*m3*y + 2*m3*z^2 + 2*m3) = qf (Q_W3_edge1_mm q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge1_mm]; grind
theorem W3_edge1_mm_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge1_mm q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge1_mm]; grind

def Q_W3_edge2_pp (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (-4*m1*q2 - 4*m1 + 4*m2*q1 - 4*m2)
  | 0, 1 => (4*m1 - 4*m2)
  | 0, 2 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 0, 3 => (4*m1*q3 - 4*m3*q1 + 4*m3)
  | 1, 0 => (4*m1 - 4*m2)
  | 1, 1 => (-4*m1*q2 + 4*m1 + 4*m2*q1 + 4*m2)
  | 1, 2 => (-4*m1*q3 + 4*m3*q1 + 4*m3)
  | 1, 3 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 2, 0 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 2, 1 => (-4*m1*q3 + 4*m3*q1 + 4*m3)
  | 2, 2 => (4*m1*q2 + 4*m1 - 4*m2*q1 - 4*m2)
  | 2, 3 => (-4*m1 - 4*m2)
  | 3, 0 => (4*m1*q3 - 4*m3*q1 + 4*m3)
  | 3, 1 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 3, 2 => (-4*m1 - 4*m2)
  | 3, 3 => (4*m1*q2 - 4*m1 - 4*m2*q1 + 4*m2)
theorem W3_edge2_pp_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 2) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((1) * Mr x y z r 0 + (1) * Mr x y z r 1 - Mr x y z r 2)) = Nn x y z * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z - 2*m1*x^2 + 4*m1*x*y + 2*m1*y^2 + 2*m1*z^2 - 4*m1*z - 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y - 2*m2*x^2 - 4*m2*x*y + 2*m2*y^2 - 2*m2*z^2 - 4*m2*z + 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y - 4*m3*x*z + 4*m3*x + 4*m3*y*z + 4*m3*y) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge2_pp_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z - 2*m1*x^2 + 4*m1*x*y + 2*m1*y^2 + 2*m1*z^2 - 4*m1*z - 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y - 2*m2*x^2 - 4*m2*x*y + 2*m2*y^2 - 2*m2*z^2 - 4*m2*z + 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y - 4*m3*x*z + 4*m3*x + 4*m3*y*z + 4*m3*y) = qf (Q_W3_edge2_pp q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge2_pp]; grind
theorem W3_edge2_pp_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge2_pp q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge2_pp]; grind

def Q_W3_edge2_pm (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (-4*m1*q2 + 4*m1 + 4*m2*q1 - 4*m2)
  | 0, 1 => (4*m1 + 4*m2)
  | 0, 2 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 0, 3 => (4*m1*q3 - 4*m3*q1 + 4*m3)
  | 1, 0 => (4*m1 + 4*m2)
  | 1, 1 => (-4*m1*q2 - 4*m1 + 4*m2*q1 + 4*m2)
  | 1, 2 => (-4*m1*q3 + 4*m3*q1 + 4*m3)
  | 1, 3 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 2, 0 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 2, 1 => (-4*m1*q3 + 4*m3*q1 + 4*m3)
  | 2, 2 => (4*m1*q2 - 4*m1 - 4*m2*q1 - 4*m2)
  | 2, 3 => (-4*m1 + 4*m2)
  | 3, 0 => (4*m1*q3 - 4*m3*q1 + 4*m3)
  | 3, 1 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 3, 2 => (-4*m1 + 4*m2)
  | 3, 3 => (4*m1*q2 + 4*m1 - 4*m2*q1 + 4*m2)
theorem W3_edge2_pm_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 2) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((1) * Mr x y z r 0 + (-1) * Mr x y z r 1 - Mr x y z r 2)) = Nn x y z * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z + 2*m1*x^2 + 4*m1*x*y - 2*m1*y^2 - 2*m1*z^2 - 4*m1*z + 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y - 2*m2*x^2 + 4*m2*x*y + 2*m2*y^2 - 2*m2*z^2 + 4*m2*z + 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y + 4*m3*x*z + 4*m3*x + 4*m3*y*z - 4*m3*y) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge2_pm_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z + 2*m1*x^2 + 4*m1*x*y - 2*m1*y^2 - 2*m1*z^2 - 4*m1*z + 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y - 2*m2*x^2 + 4*m2*x*y + 2*m2*y^2 - 2*m2*z^2 + 4*m2*z + 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y + 4*m3*x*z + 4*m3*x + 4*m3*y*z - 4*m3*y) = qf (Q_W3_edge2_pm q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge2_pm]; grind
theorem W3_edge2_pm_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge2_pm q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge2_pm]; grind

def Q_W3_edge2_mp (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (-4*m1*q2 - 4*m1 + 4*m2*q1 + 4*m2)
  | 0, 1 => (-4*m1 - 4*m2)
  | 0, 2 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 0, 3 => (4*m1*q3 - 4*m3*q1 - 4*m3)
  | 1, 0 => (-4*m1 - 4*m2)
  | 1, 1 => (-4*m1*q2 + 4*m1 + 4*m2*q1 - 4*m2)
  | 1, 2 => (-4*m1*q3 + 4*m3*q1 - 4*m3)
  | 1, 3 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 2, 0 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 2, 1 => (-4*m1*q3 + 4*m3*q1 - 4*m3)
  | 2, 2 => (4*m1*q2 + 4*m1 - 4*m2*q1 + 4*m2)
  | 2, 3 => (4*m1 - 4*m2)
  | 3, 0 => (4*m1*q3 - 4*m3*q1 - 4*m3)
  | 3, 1 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 3, 2 => (4*m1 - 4*m2)
  | 3, 3 => (4*m1*q2 - 4*m1 - 4*m2*q1 - 4*m2)
theorem W3_edge2_mp_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 2) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((-1) * Mr x y z r 0 + (1) * Mr x y z r 1 - Mr x y z r 2)) = Nn x y z * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z - 2*m1*x^2 - 4*m1*x*y + 2*m1*y^2 + 2*m1*z^2 + 4*m1*z - 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y + 2*m2*x^2 - 4*m2*x*y - 2*m2*y^2 + 2*m2*z^2 - 4*m2*z - 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y - 4*m3*x*z - 4*m3*x - 4*m3*y*z + 4*m3*y) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge2_mp_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z - 2*m1*x^2 - 4*m1*x*y + 2*m1*y^2 + 2*m1*z^2 + 4*m1*z - 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y + 2*m2*x^2 - 4*m2*x*y - 2*m2*y^2 + 2*m2*z^2 - 4*m2*z - 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y - 4*m3*x*z - 4*m3*x - 4*m3*y*z + 4*m3*y) = qf (Q_W3_edge2_mp q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge2_mp]; grind
theorem W3_edge2_mp_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge2_mp q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge2_mp]; grind

def Q_W3_edge2_mm (q1 q2 q3 m1 m2 m3 : Int) : Fin 4 → Fin 4 → Int
  | 0, 0 => (-4*m1*q2 + 4*m1 + 4*m2*q1 + 4*m2)
  | 0, 1 => (-4*m1 + 4*m2)
  | 0, 2 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 0, 3 => (4*m1*q3 - 4*m3*q1 - 4*m3)
  | 1, 0 => (-4*m1 + 4*m2)
  | 1, 1 => (-4*m1*q2 - 4*m1 + 4*m2*q1 - 4*m2)
  | 1, 2 => (-4*m1*q3 + 4*m3*q1 - 4*m3)
  | 1, 3 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 2, 0 => (4*m2*q3 - 4*m3*q2 + 4*m3)
  | 2, 1 => (-4*m1*q3 + 4*m3*q1 - 4*m3)
  | 2, 2 => (4*m1*q2 - 4*m1 - 4*m2*q1 + 4*m2)
  | 2, 3 => (4*m1 + 4*m2)
  | 3, 0 => (4*m1*q3 - 4*m3*q1 - 4*m3)
  | 3, 1 => (4*m2*q3 - 4*m3*q2 - 4*m3)
  | 3, 2 => (4*m1 + 4*m2)
  | 3, 3 => (4*m1*q2 + 4*m1 - 4*m2*q1 - 4*m2)
theorem W3_edge2_mm_div (x y z q1 q2 q3 m1 m2 m3 : Int) :
    det3 (fun r => 2 * Mr x y z r 2) (fun | 0 => m1 | 1 => m2 | 2 => m3) (fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((-1) * Mr x y z r 0 + (-1) * Mr x y z r 1 - Mr x y z r 2)) = Nn x y z * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z + 2*m1*x^2 - 4*m1*x*y - 2*m1*y^2 - 2*m1*z^2 + 4*m1*z + 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y + 2*m2*x^2 + 4*m2*x*y - 2*m2*y^2 + 2*m2*z^2 + 4*m2*z - 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y + 4*m3*x*z - 4*m3*x - 4*m3*y*z - 4*m3*y) := by
  simp only [det3, Mr, Nn]; grind
theorem W3_edge2_mm_form (x y z q1 q2 q3 m1 m2 m3 : Int) :
    2 * (-2*m1*q2*x^2 - 2*m1*q2*y^2 + 2*m1*q2*z^2 + 2*m1*q2 + 4*m1*q3*x - 4*m1*q3*y*z + 2*m1*x^2 - 4*m1*x*y - 2*m1*y^2 - 2*m1*z^2 + 4*m1*z + 2*m1 + 2*m2*q1*x^2 + 2*m2*q1*y^2 - 2*m2*q1*z^2 - 2*m2*q1 + 4*m2*q3*x*z + 4*m2*q3*y + 2*m2*x^2 + 4*m2*x*y - 2*m2*y^2 + 2*m2*z^2 + 4*m2*z - 2*m2 - 4*m3*q1*x + 4*m3*q1*y*z - 4*m3*q2*x*z - 4*m3*q2*y + 4*m3*x*z - 4*m3*x - 4*m3*y*z - 4*m3*y) = qf (Q_W3_edge2_mm q1 q2 q3 m1 m2 m3) x y z := by
  simp only [qf, Q_W3_edge2_mm]; grind
theorem W3_edge2_mm_det (q1 q2 q3 m1 m2 m3 : Int) :
    det4 (Q_W3_edge2_mm q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by
  simp only [det4, Q_W3_edge2_mm]; grind

end Cube.Detq
