#!/usr/bin/env python3
"""Generate lean/CubeBounds/Detq.lean: [P104]'s identities, for Lean's kernel to check.

`detq_check.py` verifies with sympy that every wall's quadric has a square determinant.  This
writes the same objects as Lean theorems, so that the checks are made by Lean, not by the CAS
that produced them.  Per branch Lean proves, by `grind` (commutative-ring normalisation):

  W4  (face plane of the free cube through the base triple point p; 6 branches)
      form:  wall(x,y,z) * 2 = [x y z 1] (2Q) [x y z 1]^T      the matrix represents the wall
      det:   det(2Q) = 16 (|p|^2 - 1)^2                         i.e. det Q = (|p|^2 - 1)^2
  W3  (edge of the free cube meeting the base crossing line (q, m); 12 branches)
      div:   G = N * quo                                        the division by N is exact
      form:  quo * 2 = [x y z 1] (2Q) [x y z 1]^T
      det:   det(2Q) = 16 * 16 (|m x q|^2 - 2|m|^2)^2

What remains trusted: that `wall` and `G` are the right geometric objects (the free cube's face
plane through p; the edge-meets-line condition), which is the derivation in [P104]/detq_check.py.
Regenerate:  python3 src/lean_gen_detq.py   (then `lake build` in lean/)
"""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import sympy as sp
from detq_check import M, N, form_of, x, y, z

ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, 'lean', 'CubeBounds', 'Detq.lean')


def lean(e):
    e = sp.expand(e)
    assert all(c.is_integer for c in sp.Poly(e, *sorted(e.free_symbols, key=str)).coeffs()) if e.free_symbols else e.is_integer, e
    return '(' + sp.sstr(e).replace('**', '^') + ')'


PRELUDE = """
/-- the rotation matrix of the Cayley parameter (x, y, z), times N = 1 + x^2 + y^2 + z^2 -/
def Mr (x y z : Int) : Fin 3 → Fin 3 → Int
  | 0, 0 => 1 + x^2 - y^2 - z^2 | 0, 1 => 2*(x*y - z)         | 0, 2 => 2*(x*z + y)
  | 1, 0 => 2*(x*y + z)         | 1, 1 => 1 - x^2 + y^2 - z^2 | 1, 2 => 2*(y*z - x)
  | 2, 0 => 2*(x*z - y)         | 2, 1 => 2*(y*z + x)         | 2, 2 => 1 - x^2 - y^2 + z^2
def Nn (x y z : Int) : Int := 1 + x^2 + y^2 + z^2

/-- 3x3 determinant of the columns (a, b, c) -/
def det3 (a b c : Fin 3 → Int) : Int :=
  a 0 * (b 1 * c 2 - b 2 * c 1) - b 0 * (a 1 * c 2 - a 2 * c 1) + c 0 * (a 1 * b 2 - a 2 * b 1)

/-- 4x4 determinant, cofactor expansion along row 0 -/
def det4 (q : Fin 4 → Fin 4 → Int) : Int :=
  let m (i j k : Fin 4) : Int :=
    q 1 i * (q 2 j * q 3 k - q 2 k * q 3 j) - q 1 j * (q 2 i * q 3 k - q 2 k * q 3 i)
      + q 1 k * (q 2 i * q 3 j - q 2 j * q 3 i)
  q 0 0 * m 1 2 3 - q 0 1 * m 0 2 3 + q 0 2 * m 0 1 3 - q 0 3 * m 0 1 2

/-- the quadratic form of q at (x, y, z, 1) -/
def qf (q : Fin 4 → Fin 4 → Int) (x y z : Int) : Int :=
  let v : Fin 4 → Int := fun | 0 => x | 1 => y | 2 => z | 3 => 1
  (v 0 * (q 0 0 * v 0 + q 0 1 * v 1 + q 0 2 * v 2 + q 0 3 * v 3))
  + (v 1 * (q 1 0 * v 0 + q 1 1 * v 1 + q 1 2 * v 2 + q 1 3 * v 3))
  + (v 2 * (q 2 0 * v 0 + q 2 1 * v 1 + q 2 2 * v 2 + q 2 3 * v 3))
  + (v 3 * (q 3 0 * v 0 + q 3 1 * v 1 + q 3 2 * v 2 + q 3 3 * v 3))
"""


def matdef(name, args, Q2):
    rows = []
    for r in range(4):
        for c in range(4):
            rows.append('  | %d, %d => %s' % (r, c, lean(Q2[r, c])))
    return 'def %s %s : Fin 4 → Fin 4 → Int\n%s' % (name, args, '\n'.join(rows))


SIMP = 'by simp only [det4, qf, det3, Mr, Nn]; grind'


def main():
    p1, p2, p3 = sp.symbols('p1 p2 p3')
    q1, q2, q3, m1, m2, m3 = sp.symbols('q1 q2 q3 m1 m2 m3')
    out = ['-- GENERATED by src/lean_gen_detq.py from detq_check.py\'s wall forms. Do not edit by hand.',
           '-- [P104]: every wall splits over Q because det(Q) is a perfect square identically.',
           '-- The matrices below are sympy\'s; everything they are checked AGAINST is computed by Lean.',
           '', 'namespace Cube.Detq', PRELUDE]
    p = [p1, p2, p3]
    n4 = n3 = 0
    for i in range(3):
        for sign in (1, -1):
            wall = sp.expand(sum(p[k] * M[k, i] for k in range(3)) - sign * N)
            Q2 = 2 * form_of(wall)
            d = sp.expand(Q2.det(method='berkowitz'))
            assert sp.expand(d - 16 * (p1**2 + p2**2 + p3**2 - 1)**2) == 0
            name = 'W4_axis%d_%s' % (i, 'pos' if sign > 0 else 'neg')
            out.append(matdef('Q_' + name, '(p1 p2 p3 : Int)', Q2))
            # the wall, BUILT IN LEAN from the rotation matrix: p . (column i of M) - sign N
            wall_lean = '(p1 * Mr x y z 0 %d + p2 * Mr x y z 1 %d + p3 * Mr x y z 2 %d - (%d) * Nn x y z)' % (i, i, i, sign)
            out.append('theorem %s_form (x y z p1 p2 p3 : Int) :\n    2 * %s = qf (Q_%s p1 p2 p3) x y z := by\n  simp only [qf, Q_%s, Mr, Nn]; grind'
                       % (name, wall_lean, name, name))
            out.append('theorem %s_det (p1 p2 p3 : Int) :\n    det4 (Q_%s p1 p2 p3) = 16 * (p1^2 + p2^2 + p3^2 - 1)^2 := by\n  simp only [det4, Q_%s]; grind'
                       % (name, name, name))
            out.append('')
            n4 += 1
    qv = sp.Matrix([q1, q2, q3]); mv = sp.Matrix([m1, m2, m3])
    cr = mv.cross(qv)
    target3 = 16 * 16 * (cr.dot(cr) - 2 * mv.dot(mv))**2
    for a in range(3):
        b, c = [t for t in range(3) if t != a]
        for sb in (1, -1):
            for sc in (1, -1):
                D = 2 * M[:, a]
                P = sb * M[:, b] + sc * M[:, c] - M[:, a]
                G = sp.expand(sp.Matrix.hstack(D, mv, N * qv - P).det())
                quo, rem = sp.div(sp.Poly(G, x, y, z), sp.Poly(N, x, y, z))
                assert rem.as_expr() == 0
                quo = sp.expand(quo.as_expr())
                Q2 = 2 * form_of(quo)
                assert sp.expand(sp.expand(Q2.det(method='berkowitz')) - target3) == 0
                name = 'W3_edge%d_%s%s' % (a, 'p' if sb > 0 else 'm', 'p' if sc > 0 else 'm')
                out.append(matdef('Q_' + name, '(q1 q2 q3 m1 m2 m3 : Int)', Q2))
                vs = '(x y z q1 q2 q3 m1 m2 m3 : Int)'
                # G, BUILT IN LEAN: det of the columns 2 M_a, m, N q - (sb M_b + sc M_c - M_a)
                cols = ('(fun r => 2 * Mr x y z r %d)' % a,
                        '(fun | 0 => m1 | 1 => m2 | 2 => m3)',
                        '(fun r => Nn x y z * (match r with | 0 => q1 | 1 => q2 | 2 => q3) - ((%d) * Mr x y z r %d + (%d) * Mr x y z r %d - Mr x y z r %d))'
                        % (sb, b, sc, c, a))
                out.append('theorem %s_div %s :\n    det3 %s %s %s = Nn x y z * %s := by\n  simp only [det3, Mr, Nn]; grind'
                           % (name, vs, cols[0], cols[1], cols[2], lean(quo)))
                out.append('theorem %s_form %s :\n    2 * %s = qf (Q_%s q1 q2 q3 m1 m2 m3) x y z := by\n  simp only [qf, Q_%s]; grind'
                           % (name, vs, lean(quo), name, name))
                out.append('theorem %s_det (q1 q2 q3 m1 m2 m3 : Int) :\n    det4 (Q_%s q1 q2 q3 m1 m2 m3) = 256 * ((m2*q3 - m3*q2)^2 + (m3*q1 - m1*q3)^2 + (m1*q2 - m2*q1)^2 - 2*(m1^2 + m2^2 + m3^2))^2 := by\n  simp only [det4, Q_%s]; grind'
                           % (name, name, name))
                out.append('')
                n3 += 1
    out.append('end Cube.Detq')
    open(OUT, 'w').write('\n'.join(out) + '\n')
    print('wrote %s: %d W4 branches, %d W3 branches' % (os.path.relpath(OUT, ROOT), n4, n3))


if __name__ == '__main__':
    main()
